require"user.alpha"
require"user.options"
require"user.keymaps"
require"user.plugins"
require"user.colorscheme"
require"user.lualine"
require"user.telescope"
require"user.treesitter"
require"user.autopairs"
require"user.nvim-tree"
require"user.bufferline"
require"user.coc"
require"user.toggleterm"
require"user.impatient"
require"user.whichkey"
require"user.gitsigns"
-- require"user.cmp"
-- require"user.lsp.mason"
-- require"user.lsp"
